/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import Controllers.DBController;
import Exceptions.InvalidFormException;
import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.ListSelectionModel;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author naol
 */
public class AddBusDialog extends javax.swing.JDialog {

    /**
     * Creates new form AddBusDialog
     */
    public AddBusDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadCities();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        plateNumber = new JTextField();
        jLabel3 = new JLabel();
        capacity = new JSpinner();
        addBtn = new JButton();
        cancelBtn = new JButton();
        jLabel4 = new JLabel();
        jScrollPane1 = new JScrollPane();
        citySelector = new JTable();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new Font("SF UI Display", 1, 24)); // NOI18N
        jLabel1.setText("Register a Bus");

        jLabel2.setText("Plate Number");

        jLabel3.setText("Capacity");

        addBtn.setText("ADD");
        addBtn.setActionCommand("");
        addBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.setActionCommand("");

        jLabel4.setText("Current Destination");

        citySelector.setModel(new DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        citySelector.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(citySelector);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelBtn, GroupLayout.PREFERRED_SIZE, 117, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addBtn, GroupLayout.PREFERRED_SIZE, 117, GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(capacity)
                            .addComponent(jLabel3)
                            .addComponent(plateNumber, GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)))
                    .addComponent(jScrollPane1, GroupLayout.Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plateNumber, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(capacity, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBtn, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadCities() {
        try {
            PreparedStatement ps = DBController.getPreparedStmt("SELECT * FROM City ORDER BY CityName ASC");
            ResultSet rs = ps.executeQuery();
            
            citySelector.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(AddBusDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
   
    
    private void addBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        try {
            if (plateNumber.getText().equals("") || plateNumber.getText().length() < 5) {
                throw new InvalidFormException("Please enter valid Plate Number");
            }
            
            int row = citySelector.getSelectedRow();
            String cityId_str = citySelector.getModel().getValueAt(row, 0).toString();
            int cityId = Integer.parseInt(cityId_str);
            
            PreparedStatement ps = DBController.getPreparedStmt("INSERT INTO Bus(PlateNumber, Capacity, CurrentDestination) VALUES (?, ?, ?)");
            ps.setInt(1, Integer.parseInt(plateNumber.getText()));
            ps.setInt(2, (Integer) capacity.getValue());
            ps.setInt(3, cityId);
            
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Bus Added Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
            
            this.dispose();
            
            
        }catch(InvalidFormException e) {
             JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(AddBusDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatDarkLaf.setup();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton addBtn;
    private JButton cancelBtn;
    private JSpinner capacity;
    private JTable citySelector;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JScrollPane jScrollPane1;
    private JTextField plateNumber;
    // End of variables declaration//GEN-END:variables
}
