/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import Controllers.DBController;
import Exceptions.InvalidFormException;
import Models.Agent;
import com.formdev.flatlaf.FlatDarculaLaf;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.UnsupportedEncodingException;
import java.security.NoSuchAlgorithmException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author naol
 */
public class AddUserDialog extends javax.swing.JFrame {

    /**
     * Creates new form AddUserDialog
     */
    Agent current;
    public AddUserDialog(Agent current) {
        initComponents();
        this.current = current;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        typeCombo = new JComboBox<>();
        jLabel3 = new JLabel();
        fnameField = new JTextField();
        jLabel4 = new JLabel();
        lnameField = new JTextField();
        jLabel5 = new JLabel();
        phoneNoField = new JTextField();
        jLabel6 = new JLabel();
        jLabel7 = new JLabel();
        jLabel8 = new JLabel();
        backAccountField = new JTextField();
        ssnField = new JTextField();
        jLabel9 = new JLabel();
        saveBtn = new JButton();
        cancelBtn = new JButton();
        confirmField = new JPasswordField();
        passwordField = new JPasswordField();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register new User");

        jLabel1.setFont(new Font("SF UI Display", 1, 24)); // NOI18N
        jLabel1.setText("Register new User");

        jLabel2.setText("User Type");

        typeCombo.setModel(new DefaultComboBoxModel<>(new String[] { "PASSENGER", "DRIVER" }));

        jLabel3.setText("First Name");

        jLabel4.setText("Last Name");

        jLabel5.setText("Phone Number");

        jLabel6.setText("Password");

        jLabel7.setText("Confirm Password");

        jLabel8.setText("Bank Account No.");

        jLabel9.setText("Social Security No.");

        saveBtn.setBackground(new Color(102, 153, 255));
        saveBtn.setForeground(new Color(255, 255, 255));
        saveBtn.setText("Save");
        saveBtn.setToolTipText("");
        saveBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.setToolTipText("");
        cancelBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelBtn, GroupLayout.PREFERRED_SIZE, 117, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveBtn, GroupLayout.PREFERRED_SIZE, 117, GroupLayout.PREFERRED_SIZE))
                    .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(passwordField, GroupLayout.PREFERRED_SIZE, 184, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(confirmField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(140, 140, 140)
                                .addComponent(jLabel7))
                            .addComponent(phoneNoField)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(typeCombo, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(fnameField, GroupLayout.PREFERRED_SIZE, 184, GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(0, 125, Short.MAX_VALUE))
                                    .addComponent(lnameField)))
                            .addComponent(backAccountField)
                            .addComponent(ssnField))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(typeCombo, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ssnField, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(lnameField)
                    .addComponent(fnameField, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phoneNoField, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmField, GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(passwordField, GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backAccountField, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBtn, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // Validate Forms
        try {
            String password = String.valueOf(passwordField.getPassword());
            if (ssnField.getText().length() < 9) {
                throw new InvalidFormException("SSN Should be 9 characters");
            }
            
            if (fnameField.getText().equals("") || lnameField.getText().equals("")) {
                throw new InvalidFormException("Please Enter both First and Last name");
            }
            
            if (phoneNoField.getText().length() < 10) {
                throw new InvalidFormException("Please Enter Valid Phone number");
            }
            
            if (password.equals("")) {
                throw new InvalidFormException("Please Enter your password");
            }
            
            if (password.length() < 6) {
                throw new InvalidFormException("Password should be more than 6 characters");
            }
            
            if (!password.equals(String.valueOf(confirmField.getPassword()))) {
                throw new InvalidFormException("Password and Confirmation Doesn't Match");
            }
            
            PreparedStatement ps = DBController.getPreparedStmt("INSERT INTO User(SSN, FirstName, LastName, PhoneNumber, Password, Role, BankAccountNo) VALUES (?, ?, ?, ?, ?, ?, ?)");
            ps.setInt(1, Integer.parseInt(ssnField.getText()));
            ps.setString(2, fnameField.getText());
            ps.setString(3, lnameField.getText());
            ps.setString(4, phoneNoField.getText());
            ps.setString(5, DBController.hash_md5(String.valueOf(passwordField.getPassword())));
            ps.setString(6, (String) typeCombo.getSelectedItem());
            ps.setString(7, backAccountField.getText());
            
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(this, (String) typeCombo.getSelectedItem()  + " Added Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
            
            this.dispose();
            new AgentDashboard(current).setVisible(true);
            
            
        }catch(InvalidFormException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error in Form", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "SQL Error", "SQL Error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(AddUserDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(AddUserDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(AddUserDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void cancelBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.dispose();
        AgentDashboard ad = new AgentDashboard(current);
        ad.setVisible(true);
    }//GEN-LAST:event_cancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatDarculaLaf.setup();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JTextField backAccountField;
    private JButton cancelBtn;
    private JPasswordField confirmField;
    private JTextField fnameField;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JTextField lnameField;
    private JPasswordField passwordField;
    private JTextField phoneNoField;
    private JButton saveBtn;
    private JTextField ssnField;
    private JComboBox<String> typeCombo;
    // End of variables declaration//GEN-END:variables
}
